idf_component_register(SRCS "main.c" "nvs_handler.c" "esp_now_logic.c"
                    INCLUDE_DIRS "."
vostok-nexus-v5-1-ultra-premium-initial-5231716576209781774
                    PRIV_REQUIRES nvs_flash esp_wifi esp_event esp_http_server esp_now json
)

                    PRIV_REQUIRES esp_http_server esp_wifi nvs_flash)
 main
